name: Update Counter

on:
  push:
    paths:
      - 'counter.json'

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add counter.json
          git commit -m "Update visit counter" || exit 0
          git push 